### ISSUE TITLE
[Feature request] Support for ARM

### ISSUE THREAD

**Issue by themorlan** [waja/docker-calcardbackup#2]
Will there be a chance to have this docker available on ARM-machines?

Thanks and Greetings!

**Comment by waja** [comment]
Hi @themorlan,

thanks for asking. Actually I think I don't have time to work on this, so not on short term. If you have any documentation how to implement that with automated builds, feel free to come up with it. You can also send PR's if you want to.

Cheers, Jan.

**Comment by themorlan** [comment]
Hey @waja,
thanks for the reply! Actually I dont know anything about software development so I'm not able to contribute in any form I'm afraid. 
Still thank you very much for your work!

**Comment by themorlan** [comment]
Hi @waja,
I could not let this issue rest. So in the last days I tried to port your docker to ARM-architecture which worked quite easily since the windows client of docker now support docker build for ARM. I was even able to create a docker manifest so the right image gets pulled according to your architecture.
Then I tried to implenment automated builds by forking your project (https://github.com/themorlan/docker-calcardbackup), but unfortunately failed. I found some resources about this topic (https://aquarat.co.za/tag/autobuild/ https://stackoverflow.com/questions/54578066/how-to-build-a-docker-image-on-a-specific-architecture-with-docker-hub) but I was not able to get the inbuild emulator (qemu-user-static) to run. The docker build command executed from a Linux-VM always ended with an exec failed-error.
If you find the time, maybe you have an idea to solve this?!

**Comment by waja** [comment]
https://mirailabs.io/blog/multiarch-docker-with-buildx/

**Comment by waja** [comment]
https://github.com/Cyconet/docker-calcardbackup/pull/4 is still pending for now

**Comment by themorlan** [comment]
> 
> 
> https://mirailabs.io/blog/multiarch-docker-with-buildx/

Very interesting article. This makes things easier in the future. I'm gonna play with a little.

**Comment by waja** [comment]
fixed by 278b634119816e068240d6cc3477537515004abf
