### ISSUE TITLE
-z | --zip option not supported

### ISSUE THREAD

**Issue by Jaryd** [waja/docker-calcardbackup#73]
When setting the -z option in the docker compse CALCARD_OPTS (e.g.: -i -r 20 -z)
An Error is thrown during first run, that package 'zip' isn't available.
Afterwards it packages as a tar.gz normally

Log from container:

=> Create a backup on the startup

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+

+  Sun Jun 18 10:56:36 UTC 2023 --> START calcardbackup ver. 5.3.0 (14.06.2023), AGPL-3.0

+  Checking dependencies and preparing...

[...]

/opt/calcardbackup/calcardbackup: line 422: zip: command not found

-- NOTICE: package 'zip' is not available. Using 'tar.gz' as compression method.

[...]

**Comment by waja** [comment]
Hi @Jaryd,

please give the [development tag](https://github.com/users/waja/packages/container/calcardbackup/101788136?tag=development) a try.
